allow-licenses:
  - 0BSD
  - Apache-2.0
  - Apache-2.0 WITH LLVM-exception
  - BSD-2-Clause
  - BSD-3-Clause
  - BSL-1.0
  - CC0-1.0
  - ISC
  - MIT
  - MIT OR Apache-2.0
  - LGPL-2.1-only
  - LGPL-2.1-or-later
  - LGPL-3.0-only
  - LGPL-3.0-or-later
  - MPL-2.0
  - Unicode-3.0
  - Unlicense
  - Zlib
allow-dependencies-licenses:
  - pkg:cargo/rust-argon2
