sonar.projectKey=SchnitzelAndSpaetzle_mithril-vault
sonar.organization=schnitzelandspaetzle

sonar.sources=src,src-tauri/src
sonar.tests=src,src-tauri/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx

sonar.exclusions=node_modules/**,**/*.d.ts,dist/**,coverage/**,src-tauri/target/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.rust.lcov.reportPaths=src-tauri/rust-lcov.info
