/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as OpenDbRouteImport } from './routes/open-db'
import { Route as NewDbRouteImport } from './routes/new-db'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'

const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenDbRoute = OpenDbRouteImport.update({
  id: '/open-db',
  path: '/open-db',
  getParentRoute: () => rootRouteImport,
} as any)
const NewDbRoute = NewDbRouteImport.update({
  id: '/new-db',
  path: '/new-db',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new-db': typeof NewDbRoute
  '/open-db': typeof OpenDbRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new-db': typeof NewDbRoute
  '/open-db': typeof OpenDbRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new-db': typeof NewDbRoute
  '/open-db': typeof OpenDbRoute
  '/password-generator': typeof PasswordGeneratorRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new-db' | '/open-db' | '/password-generator' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new-db' | '/open-db' | '/password-generator' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/new-db'
    | '/open-db'
    | '/password-generator'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewDbRoute: typeof NewDbRoute
  OpenDbRoute: typeof OpenDbRoute
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-db': {
      id: '/open-db'
      path: '/open-db'
      fullPath: '/open-db'
      preLoaderRoute: typeof OpenDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-db': {
      id: '/new-db'
      path: '/new-db'
      fullPath: '/new-db'
      preLoaderRoute: typeof NewDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewDbRoute: NewDbRoute,
  OpenDbRoute: OpenDbRoute,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
