/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PasswordGeneratorRouteImport } from './routes/password-generator'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as authOpenDbRouteImport } from './routes/(auth)/open-db'
import { Route as authNewDbRouteImport } from './routes/(auth)/new-db'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as DashboardEntryNewRouteImport } from './routes/dashboard/entry/new'
import { Route as DashboardEntryEditRouteImport } from './routes/dashboard/entry/edit'
import { Route as DashboardEntryIdRouteImport } from './routes/dashboard/entry/$id'

const PasswordGeneratorRoute = PasswordGeneratorRouteImport.update({
  id: '/password-generator',
  path: '/password-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => authRouteRoute,
} as any)
const authOpenDbRoute = authOpenDbRouteImport.update({
  id: '/open-db',
  path: '/open-db',
  getParentRoute: () => authRouteRoute,
} as any)
const authNewDbRoute = authNewDbRouteImport.update({
  id: '/new-db',
  path: '/new-db',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const DashboardEntryNewRoute = DashboardEntryNewRouteImport.update({
  id: '/entry/new',
  path: '/entry/new',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEntryEditRoute = DashboardEntryEditRouteImport.update({
  id: '/entry/edit',
  path: '/entry/edit',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEntryIdRoute = DashboardEntryIdRouteImport.update({
  id: '/entry/$id',
  path: '/entry/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/password-generator': typeof PasswordGeneratorRoute
  '/login': typeof authLoginRoute
  '/new-db': typeof authNewDbRoute
  '/open-db': typeof authOpenDbRoute
  '/': typeof authIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/dashboard/entry/$id': typeof DashboardEntryIdRoute
  '/dashboard/entry/edit': typeof DashboardEntryEditRoute
  '/dashboard/entry/new': typeof DashboardEntryNewRoute
}
export interface FileRoutesByTo {
  '/password-generator': typeof PasswordGeneratorRoute
  '/login': typeof authLoginRoute
  '/new-db': typeof authNewDbRoute
  '/open-db': typeof authOpenDbRoute
  '/': typeof authIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/dashboard/entry/$id': typeof DashboardEntryIdRoute
  '/dashboard/entry/edit': typeof DashboardEntryEditRoute
  '/dashboard/entry/new': typeof DashboardEntryNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/password-generator': typeof PasswordGeneratorRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/new-db': typeof authNewDbRoute
  '/(auth)/open-db': typeof authOpenDbRoute
  '/(auth)/': typeof authIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/dashboard/entry/$id': typeof DashboardEntryIdRoute
  '/dashboard/entry/edit': typeof DashboardEntryEditRoute
  '/dashboard/entry/new': typeof DashboardEntryNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/password-generator'
    | '/login'
    | '/new-db'
    | '/open-db'
    | '/'
    | '/dashboard/'
    | '/settings'
    | '/dashboard/entry/$id'
    | '/dashboard/entry/edit'
    | '/dashboard/entry/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/password-generator'
    | '/login'
    | '/new-db'
    | '/open-db'
    | '/'
    | '/dashboard'
    | '/settings'
    | '/dashboard/entry/$id'
    | '/dashboard/entry/edit'
    | '/dashboard/entry/new'
  id:
    | '__root__'
    | '/(auth)'
    | '/dashboard'
    | '/password-generator'
    | '/(auth)/login'
    | '/(auth)/new-db'
    | '/(auth)/open-db'
    | '/(auth)/'
    | '/dashboard/'
    | '/settings/'
    | '/dashboard/entry/$id'
    | '/dashboard/entry/edit'
    | '/dashboard/entry/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  PasswordGeneratorRoute: typeof PasswordGeneratorRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/password-generator': {
      id: '/password-generator'
      path: '/password-generator'
      fullPath: '/password-generator'
      preLoaderRoute: typeof PasswordGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/open-db': {
      id: '/(auth)/open-db'
      path: '/open-db'
      fullPath: '/open-db'
      preLoaderRoute: typeof authOpenDbRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/new-db': {
      id: '/(auth)/new-db'
      path: '/new-db'
      fullPath: '/new-db'
      preLoaderRoute: typeof authNewDbRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dashboard/entry/new': {
      id: '/dashboard/entry/new'
      path: '/entry/new'
      fullPath: '/dashboard/entry/new'
      preLoaderRoute: typeof DashboardEntryNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/entry/edit': {
      id: '/dashboard/entry/edit'
      path: '/entry/edit'
      fullPath: '/dashboard/entry/edit'
      preLoaderRoute: typeof DashboardEntryEditRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/entry/$id': {
      id: '/dashboard/entry/$id'
      path: '/entry/$id'
      fullPath: '/dashboard/entry/$id'
      preLoaderRoute: typeof DashboardEntryIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authNewDbRoute: typeof authNewDbRoute
  authOpenDbRoute: typeof authOpenDbRoute
  authIndexRoute: typeof authIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authNewDbRoute: authNewDbRoute,
  authOpenDbRoute: authOpenDbRoute,
  authIndexRoute: authIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEntryIdRoute: typeof DashboardEntryIdRoute
  DashboardEntryEditRoute: typeof DashboardEntryEditRoute
  DashboardEntryNewRoute: typeof DashboardEntryNewRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEntryIdRoute: DashboardEntryIdRoute,
  DashboardEntryEditRoute: DashboardEntryEditRoute,
  DashboardEntryNewRoute: DashboardEntryNewRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  PasswordGeneratorRoute: PasswordGeneratorRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
